[package]
name = "xplist"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true
description = "An XML-based property list serializer and deserializer"

[dependencies]
plist-types = "0.1.0"
quick-xml    = "0.36"
base64       = "0.22"
thiserror.workspace = true

[dev-dependencies]
binplist = { path = "../binplist" }
