[package]
name = "plutil"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true
description = "A library implementing a subset of Apple's plutil binary functionality using the xplist and bplist crates"

[[bin]]
name = "plutil"
path = "src/main.rs"

[dependencies]
plist-types = "0.1.0"
binplist    = "0.1.0"
xplist      = "0.1.0"
clap        = { version = "4", features = ["derive"] }
thiserror.workspace = true
