[package]
name = "plutil"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true
description = "A library implementing a subset of Apple's plutil binary functionality using the xplist and bplist crates"

[[bin]]
name = "plutil"
path = "src/main.rs"

[dependencies]
plist-types = { path = "../plist-types" }
binplist    = { path = "../binplist" }
xplist      = { path = "../xplist" }
clap        = { version = "4", features = ["derive"] }
thiserror.workspace = true
